version: '3.8'

services:
  api:
    container_name: api_service
    build:
      context: .
      target: production
      dockerfile: ./apps/api/Dockerfile
    env_file:
      - .env
    ports:
      - '8000:3000'
    depends_on:
      - prisma
      - postgres
      - rabbitmq

  chat:
    container_name: chat_service
    build:
      context: .
      target: production
      dockerfile: ./apps/chat/Dockerfile
    env_file:
      - .env
    ports:
      - '8001:3000'
    depends_on:
      - api
      - prisma
      - postgres
      - rabbitmq

  prisma:
    image: prismagraphql/prisma:1.34.9-gatsby
    restart: always
    ports:
      - '4466:4466'
    environment:
      SLOW_QUERIES_LOGGING: 'true'
      SLOW_QUERIES_LOGGING_THRESHOLD: '0'
      PRISMA_CONFIG: |
        managementApiSecret: mysercretapi123
        port: 4466
        databases:
          default:
            connector: ${DATABASE_CONNECTOR}
            host: ${DB_HOST}
            port: ${DB_PORT}
            user: ${DB_USER}
            password: ${DB_PASS}
            connectionLimit: ${CONNECTION_LIMIT}

  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_DB: ${DB_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - '5672:5672'  # AMQP
      - '15672:15672'  # RabbitMQ management
    environment:
      RABBITMQ_DEFAULT_USER: myrabbituser
      RABBITMQ_DEFAULT_PASS: mypassword123
